name: CI/CD Pipeline - EFT DevOps

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código fuente
      uses: actions/checkout@v3

    # --- ETAPA DE CONFIGURACIÓN Y TEST ---
    - name: Configurar entorno de Node.js (Test)
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: './backJs/package-lock.json'

    - name: Instalar Dependencias del Backend Node.js
      run: |
        cd backJs
        npm ci

    # --- ETAPA DE AUTENTICACIÓN EN EL REGISTRO ---
    - name: Iniciar sesión en Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # --- ETAPA DE EMPAQUETADO Y PUBLICACIÓN (BUILD & PUSH) ---
    - name: Construir y Publicar Imagen del Backend Node.js
      uses: docker/build-push-action@v4
      with:
        context: ./backJs
        file: ./backJs/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/eft-backend:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/eft-backend:${{ github.sha }}

    - name: Construir y Publicar Imagen del Frontend
      uses: docker/build-push-action@v4
      with:
        context: ./Front
        file: ./Front/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/eft-frontend:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/eft-frontend:${{ github.sha }}

    - name: Construir y Publicar Imagen del Backend Python
      uses: docker/build-push-action@v4
      with:
        context: ./BackPy
        file: ./BackPy/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/eft-backend-python:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/eft-backend-python:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout del código fuente
      uses: actions/checkout@v3

    # 1. Autenticar de forma real en tu AWS Learner Lab usando tus Secretos
    - name: Configurar credenciales de AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    # 2. Descargar la definición de tarea que creamos en la consola de AWS
    - name: Descargar Task Definition activa de AWS
      run: |
        aws ecs describe-task-definition --task-definition eft-task --query taskDefinition > task-definition.json

    # 3. ELIMINAR EL PARÁMETRO CONFLICTIVO CON JQ
    - name: Remover clave conflictiva para ECS
      run: |
        jq 'del(.enableFaultInjection)' task-definition.json > clean-task-definition.json

    # 4. Actualizar la definición de la tarea para usar la nueva imagen limpia
    - name: Actualizar URI de la imagen en la Task Definition
      id: render-task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: clean-task-definition.json
        container-name: eft-container
        image: ${{ secrets.DOCKERHUB_USERNAME }}/eft-backend:latest

    # 5. Desplegar de verdad en el servicio Express de tu clúster "default"
    - name: Desplegar nueva versión en AWS ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.render-task-def.outputs.task-definition }}
        service: nginx-98c0
        cluster: default
        wait-for-service-stability: false
